### ISSUE TITLE
avoid strlen() on encoding functions

### ISSUE THREAD

**Issue by edsiper** [nigels-com/tutf8e#2]
for performance reasons, would be good to let the caller pass the string length than calculate it on every call, ref:

https://github.com/nigels-com/tutf8e/blob/master/src/iso_8859_14.c#L26

**Comment by nigels-com** [comment]
Yes, I was for a while looking to align with the iconv API.  The rationale for the current arrangement is to support both NUL-terminated and known-length strings that might not be NUL-terminated.  I'm leaning towards generating optimal code for both of these use cases, rather than requiring one or the other.

**Comment by edsiper** [comment]
note that if you force to pass the string length, you will let the caller provide that information for you. I don't think is necessary to support string length calculation in the API.

**Comment by nigels-com** [comment]
Done.

For now it's generating two functions per encoding - one for NUL-terminated string of unknown length, one for known length buffer.

```
int tutf8e_string_encode_iso_8859_1(char *output, size_t olen, const char *input)
{
  size_t len = strlen(input) + 1;
  return tutf8e_buffer_encode(iso_8859_1_utf8, input, len, output, olen);
}

int tutf8e_buffer_encode_iso_8859_1(char *output, size_t olen, const char *input, size_t ilen)
{
  return tutf8e_buffer_encode(iso_8859_1_utf8, input, ilen, output, olen);
}
```
